GET http://localhost:3000/tags

###
Post http://localhost:3000/tag
Content-Type: application/json

 {"name": "bleu"}

###

Put http://localhost:3000/tag/3
Content-Type: application/json

 {"name": "rouge"}

###
Delete http://localhost:3000/tag/3
